name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-09"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=..."
JWT_SECRET="myjwtsecret"
